#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

if (file_exists(__DIR__ . '/yii-local')) include __DIR__ . '/yii-local';

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$profile = YII_DEBUG;
$profile and Yii::beginProfile('run');

// $application = new yii\console\Application($config);
$application = new \shopack\base\common\console\Application($config);
$exitCode = $application->run();

$profile and Yii::endProfile('run');

exit($exitCode);
